services:
  app:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
      args:
        NODE_ENV: development
    env_file: .env
    environment:
      MONGODB_URI: mongodb://mongo:27017/appdb
      SESSION_STORE_URI: mongodb://mongo:27017/appdb
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./uploads:/usr/src/app/uploads
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped

  mongo:
    image: mongo:noble
    command: ["--wiredTigerCacheSizeGB", "0.5"]
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mongo_data: